# PLC采集平台 Docker Compose 配置
version: '3.8'

services:
  # Nginx反向代理服务
  nginx:
    image: nginx:alpine
    container_name: plc-admin-nginx
    ports:
      - "8088:8088"
      # - "443:443"  # HTTPS端口（如需要）
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./ssl:/etc/nginx/ssl  # SSL证书目录（如需要）
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - plc-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8088"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plc-admin-backend
    # 移除端口映射，只在内部网络中访问
    expose:
      - "8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - SQLITE_DATABASE_URL=sqlite:///./data/plc_admin.db
      - CORS_ORIGINS=http://zyg.yunziheng.xyz,https://zyg.yunziheng.xyz,http://nginx,http://frontend:3000
    restart: unless-stopped
    networks:
      - plc-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: plc-admin-frontend
    # 移除端口映射，只在内部网络中访问
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - plc-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# 网络配置
networks:
  plc-network:
    driver: bridge
    name: plc-admin-network

# 数据卷配置
volumes:
  plc-data:
    driver: local
    name: plc-admin-data
  plc-logs:
    driver: local
    name: plc-admin-logs